### ISSUE TITLE
zeus generates empty coverage results with simplecov

### ISSUE THREAD

**Issue by xhh** [burke/zeus#131]
I'm using zeus with rspec and simplecov (for ruby 1.9) in a rails 3 project, and executing

```
zeus rspec spec
```

generates empty testing coverage results in coverage/index.html. It is OK when running the tests without zeus.

**Comment by guapolo** [comment]
@Johaned suggestion worked form me using Rails 4, Zeus 0.15.4, ruby 2.2.

Is it ok if I edit the Wiki page to reflect this solution when using Rails >= 4

**Comment by Johaned** [comment]
hey @guapolo 
sure, no problem :+1:

**Comment by xero88** [comment]
This is not working for me. 

I get : 

> You tried to define an enum named "available_roles" on the model "User", but this will generate a instance method "admin?", which is already defined by another enum. (ArgumentError)

**Comment by guapolo** [comment]
@xero88 that's a Rails enum thing. You defined two enums on your model with an element named `:admin`. You can't repeat enum element names on the same model.

**Comment by xero88** [comment]
@guapolo no I have not. When I change the element, I get : 

`You tried to define an enum named "available_roles" on the model "User", but this will generate a instance method "adminaa?", which is already defined by another enum. (ArgumentError)`
