### ISSUE TITLE
The gem shoulda-matchers does not work

### ISSUE THREAD

**Issue by terlar** [burke/zeus#134]
When running specs with `zeus rspec` all tests using shoulda-matchers fail.

I get the error message with _undefined method_ which is the same as if `shoulda-matchers` weren't loaded.

Do I need to configure something special to get this to work with `zeus`? Works perfectly fine with bare `rspec`.

The only thing I have right now specific to the shoulda-matchers is the following code in my `Gemfile` and my specs of course.

``` ruby
group :test do
  gem 'shoulda-matchers'
end
```

**Comment by lukerollans** [comment]
Moving `rspec-rails` next to `shoulda-matchers` in my `:test` group did not work, however @michaelglass's solution did indeed work for me (require false in gemfile and manually requiring in `spec_helper.rb`

**Comment by gmonfort** [comment]
+1 to @michaelglass solution

**Comment by Andrelton** [comment]
Another +1 to the @michaelglass solution, thank you!

**Comment by AlejandroFernandesAntunes** [comment]
it started working for me when adding the following to rails_helper:
```

Shoulda::Matchers.configure do |config|
  config.integrate do |with|
    with.test_framework :rspec
    with.library :rails
  end
end

```
which was in the readme file
