### ISSUE TITLE
Clean up termios settings more aggressively on exit

### ISSUE THREAD

**Issue by burke** [burke/zeus#173]
#124
#144
#137
#128
#170

**Comment by gerrywastaken** [comment]
@burke #137 was apparently moved here, but I'm still having the issue with new lines being ignored (as described in 137).

**Comment by longkt90** [comment]
@gerrywastaken Seems like it only happens on some version of ruby, mine working fine on 2.3.1 but this issue happen on 2.3.0. I end up add the readline lib and it works fine. https://github.com/guard/guard/wiki/Add-Readline-support-to-Ruby-on-Mac-OS-X 

The simplest way is just add  `gem 'rb-readline'` to your development Gemfile

**Comment by gerrywastaken** [comment]
@longkt90 Yeah it seems I was using 2.3.0 back when I posted that. Great to hear about the fix and work around. Thanks. :)

**Comment by paulbhartzog** [comment]
As of March 2017 this issue still exists.  Zeus returns to terminal but the output is all botched.

`gem install rb-readline` seems to be a valid workaround, but it would be nice to see this fixed in zeus internally.  Thx. :-)

**Comment by sideshowcoder** [comment]
Yep definitely I thought I caught some problems with the last release but apparently not all still :(

**Comment by TheZoq2** [comment]
`gem instal rb-readline` makes the zeus output correct but any other commands run after it have incorrect output.
