### ISSUE TITLE
Errors Still Not Actually Being Displayed

### ISSUE THREAD

**Issue by IAmFledge** [burke/zeus#208]
Upon running zeus start, it is failing with output that doesn't actually inform me of anything. I have no way of knowing what's going on when it's falling over.

![Screenshot 13:12:2012 12:44](https://f.cloud.github.com/assets/768254/10534/d49d400c-4522-11e2-8018-a11971f1c6a3.png)
Starting Zeus server
[ready] [crashed] [running] [connecting] [waiting]
boot
└── default_bundle
    ├── test_environment
    │   └── test_helper
    └── development_environment
        └── prerake

Available Commands: [waiting] [crashed] [ready]
zeus test (alias: rspec, testrb) [run to see backtrace]
zeus rake [run to see backtrace]
zeus runner (alias: r) [run to see backtrace]
zeus generate (alias: g) [run to see backtrace]
zeus server (alias: s) [run to see backtrace]
zeus dbconsole [run to see backtrace]
zeus console (alias: c) [run to see backtrace]
Failed to initialize application from zeus.json.
The json file is valid, but the command could not be started:

**Comment by sideshowcoder** [comment]
Ok I think this is resolved so I'm gonna close it.

**Comment by xero88** [comment]
How resolve this ?

I get : run to see backtrace

Run what ?
