### ISSUE TITLE
"exit status 1" on startup

### ISSUE THREAD

**Issue by rubysolo** [burke/zeus#237]
Hello--

I'm trying to get started with using Zeus in my workflow.  My environment is OSX 10.7.5, Ruby 1.9.3-p327,  Rails 3.2.11, Zeus version 0.13.2.  When I execute "zeus start", I get the status screen with everything in waiting status.  At the bottom of the screen, I get "exit status 1" briefly, then the commands shift down one line to cover it up, and it hangs in that state indefinitely.  What can I do to troubleshoot?

**Comment by marcpursals** [comment]
Same issue here. For me worked:

1. removing zeus from gemfile
2. bundle install
3. adding zeus to gemfile
4. bundle install

done.

**Comment by hraynaud** [comment]
@marcpursals 
Thanks for the advice.  This worked for me.
@latortuga  
Is there any downside to install zeus in the Gemfile vs globally?
Thanks

**Comment by latortuga** [comment]
I always install it globally in every new ruby I install. I don't think there's really a problem either way.

**Comment by rguerrettaz** [comment]
Tried literally everything stated above except adding zeus to my Gemfile. Gave in, added it, works now...

**Comment by averyga** [comment]
Bundle install helped.

**Comment by shevaun** [comment]
ruby 2.1.6p336
zeus v0.15.4

@theodorton's advice fixed it for me:

```
$ gem uninstall json

Select gem to uninstall:
 1. json-1.8.1
 2. json-1.8.2
 3. All versions
> 3
Successfully uninstalled json-1.8.1
Successfully uninstalled json-1.8.2
$  gem install json -v 1.7.7
Fetching: json-1.7.7.gem (100%)
Building native extensions.  This could take a while...
Successfully installed json-1.7.7
1 gem installed
```

**Comment by rahilsondhi** [comment]
`bundle update guard-zeus` fixed it for me

**Comment by ssoroka-se** [comment]
There's a lot of "try this" in here, but no actual debugging steps. Here's how you can find the actual issue:

`zeus --log ZEUS.LOG start` then `cat ZEUS.LOG`

**Comment by markalfred** [comment]
@ssoroka-se :+1: :+1: :+1: :+1: :exclamation:

**Comment by JHanley85** [comment]
@ssoroka-se :+1:

**Comment by shelkem** [comment]
@marcpursals 
Thanks for the advice. This worked for me.

**Comment by MaximilianoFelice** [comment]
Still getting this error after trying every possible combination of answers in this issue.

Does anyone have an idea of where this bug is comming from? It's been more than two years from the original post and it doesn't seem to be any official solution.

**Comment by ntdb** [comment]
@marcpursals this worked for me as well. Thanks!

**Comment by fishbullet** [comment]
i have issue with `exit status 1`, when i try to install it globaly(not in `Gemfile`). 
Run `zeus --log ZEUS.LOG start` show me an actual problem, `Could not find 'json' (= 1.8.3) - did find: [json-1.8.1]` install/reinstall a `json` gem not help me. 

To make it work i do:
```
gem uninstall method_source
gem install method_source -v '= 0.6.7'
```
Now it's works.

**Comment by aeberlin** [comment]
I had this issue with `zeus-parallel_tests` but none of the steps above resolved it. After checking my logs, `load_file` wasn't being found in `load_tracking.rb`, with a custom plan. I fixed it by running `bundle update psych` and adding `require 'yaml'` to the top of my custom plan.

**Comment by radar** [comment]
I just got this today. Following @ssoroka-se's advice, I see this:

```
2015/11/21 10:21:58.583514 [/Users/nick/Work/gopath/src/github.com/burke/zeus/go/processtree/slavenode.go:184] boot/(no PID) in unbooted state
2015/11/21 10:21:58.584299 [/Users/nick/Work/gopath/src/github.com/burke/zeus/go/processtree/slavenode.go:372] boot/(no PID) running the root command now
2015/11/21 10:21:58.739034 [/Users/nick/Work/gopath/src/github.com/burke/zeus/go/processtree/slavenode.go:383] boot/(no PID) root process exited with an error before it could boot: exit status 1; output was: /Users/ryanbigg/.gem/ruby/2.2.3/gems/zeus-0.15.4/lib/zeus/load_tracking.rb:58:in `alias_method': undefined method `load_file' for class `Module' (NameError)
        from /Users/ryanbigg/.gem/ruby/2.2.3/gems/zeus-0.15.4/lib/zeus/load_tracking.rb:58:in `singleton class'
        from /Users/ryanbigg/.gem/ruby/2.2.3/gems/zeus-0.15.4/lib/zeus/load_tracking.rb:57:in `<module:YAML>'
        from /Users/ryanbigg/.gem/ruby/2.2.3/gems/zeus-0.15.4/lib/zeus/load_tracking.rb:56:in `<top (required)>'
        from /Users/ryanbigg/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /Users/ryanbigg/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /Users/ryanbigg/.gem/ruby/2.2.3/gems/zeus-0.15.4/lib/zeus.rb:13:in `<top (required)>'
        from /Users/ryanbigg/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /Users/ryanbigg/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /Users/ryanbigg/.gem/ruby/2.2.3/gems/zeus-0.15.4/lib/zeus/rails.rb:12:in `<top (required)>'
        from /Users/ryanbigg/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from /Users/ryanbigg/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /Users/ryanbigg/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
```

**Comment by radar** [comment]
Removing method_source 0.8.2 and using method_source 0.8.1 fixed this issue for me.

**Comment by pietdaniel** [comment]
Im still receiving this error, I have a `zeus.json` which when I remove the error is resolved. I can also empty and reinstall my gemset which revolves the issue but this can be rather cumbersome. Here is the output from the zeus log:

```
2016/01/04 10:13:39.934241 [/Users/nick/Work/gopath/src/github.com/burke/zeus/go/processtree/slavenode.go:184] boot/(no PID) in unbooted state
2016/01/04 10:13:39.934709 [/Users/nick/Work/gopath/src/github.com/burke/zeus/go/processtree/slavenode.go:372] boot/(no PID) running the root command now
2016/01/04 10:13:40.705920 [/Users/nick/Work/gopath/src/github.com/burke/zeus/go/processtree/slavenode.go:383] boot/(no PID) root process exited with an error before it could boot: exit status 1; output was: /Users/piet/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:34:in `block in setup': You have already activated faraday 0.9.2, but your Gemfile requires faraday 0.9.1. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
        from /Users/piet/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/runtime.rb:19:in `setup'
        from /Users/piet/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler.rb:127:in `setup'
        from /Users/piet/.rvm/gems/ruby-2.2.3@global/gems/bundler-1.10.6/lib/bundler/setup.rb:18:in `<top (required)>'
        from /Users/piet/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /Users/piet/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

**Comment by richkettle** [comment]
I have found that this can occur when switching gemsets but not exiting the current dir.

**Comment by bf4** [comment]
For me, the issue was the json gem.  I have zeus installed outside of my app and not in the gemfile.

```
zeus --log ZEUS.LOG start
```

 then `cat ZEUS.LOG` showed


```
~/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'json' (= 1.8.6) - did find: [json-1.8.3,json-1.8.1] (Gem::LoadError)
```

then `gem install json -v '1.8.6'` and I could start zeus again! 

On CRuby 2.2.5.

My Gemfile has the json gem locked to 1.8.6, which I guess matters because of some breaking changes in that version

**Comment by Catharz** [comment]
@bf4's solution resolved for me in a round-about way.

The logs pointed to having multiple versions of pry installed. The Gemfile one was earlier than the system Ruby version. Uninstalling the system Ruby version of pry resolved the issue.

**Comment by mooreds** [comment]
So, I ran into this same issue, again with versions of gems (pry in particular, but I only went part way down the path of tracking the exact gems) being different in the system and in the Gemfile.lock.  I'd previously done a 'bundle update' and even when I re checked out the Gemfile.lock and did a bundle install, the newer versions were being picked up by zeus.

For future reference, I solved this by re-installing rvm to clean up my entire path, and then running bundle install.

**Comment by AnwarShah** [comment]
For me, the problem was I had coderay 1.12 and 1.11 installed, one for rails5 and another for rails4. I've installed both gems on default gemset and zeus was trying to use coderay 1.12 which caused problem. I found that by running `zeus --log /dev/stderr start` command.

Then I've created another gemset for rails4 only and installed the gems again. Now, it's starting just fine, since I'm using this gemset.

I used this guide to create the gemset. It's quite easy https://rvm.io/gemsets/creating

**Comment by rachel-carvalho** [comment]
I'm just leaving this here for other people who might be having the same problem. I'm on `zeus  v0.15.15.pre` since November, but when I updated to `ruby 2.5`, I started seeing the error `cannot load such file -- ubygems (LoadError)`, just like @Goltergaul above.

My error message didn't say anything about `zeus.json`, but his did, so I looked at my `zeus.json` file and the problem was that my command seemed to have the wrong syntax. So I changed from:
```json
"command": "ruby -rubygems -r./zeus_custom_plan -eZeus.go"
```
to
```json
"command": "ruby -r rubygems -r ./zeus_custom_plan -e Zeus.go"
```
And it's now working.

**Comment by AndrzejJantos** [comment]
Hello,
I had installed new Ruby version 2.5.0 on my mac and zeus is breaking on this error.
Nothing is helping, even on total new rails app, it doesn't work. Please help :)

**Comment by sobrinho** [comment]
I'm seeing this:

```
/Users/sobrinho/.rbenv/versions/2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2322:in `check_version_conflict': can't activate method_source-0.8.2, already activated method_source-0.9.0 (Gem::LoadError)
```

**Comment by edk** [comment]
Using ruby 2.5.1 and rails 5, the more recent comments above pointed me to:
```
zeus --log ZEUS.LOG start
```
which showed a require problem.  The ruby line from `zeus init` created:
```
  "command": "ruby -rubygems -r./custom_plan -eZeus.go",
```
which should be
```
  "command": "ruby -rrubygems -r./custom_plan -eZeus.go",
```

That fixed my issue

**Comment by adfineberg** [comment]
I had the same as @sobrinho (with different versions of method_source) - did these steps which worked:

1. I removed the relevant gems from my Gemfile that used method_source (in my case it was only pry, check in Gemfile.lock). 
2. Run `bundle`
3. Add the gems back
4. Run `bundle` once again
5. `zeus start`

**Comment by os6sense** [comment]
Just came to mention this issue and the solution - suprised its unfixed ...

**Comment by zhisme** [comment]
@edk pointed out the fix.
and the issue comes from here.

https://thoughtbot.com/blog/improving-rails-boot-time-with-zeus#set-up

**Comment by vassyz** [comment]
What I did to fix `can't activate method_source-0.8.2, already activated method_source-0.9.2`: 
```shell
gem uninstall method_source -v 0.9.2
```

It's because I had multiple `pry` versions installed on my machine. Hopefully the activated version of the gem is not a hard dependency for your project.

**Comment by shimaamarzouk** [comment]
Thanks @ssoroka-se for the debugging tip
Changing "command": "ruby -r -r./custom_plan -eZeus.go", to "command": "ruby -r ./custom_plan -eZeus.go", in `zeus.json` solved in my case

**Comment by diegoesp** [comment]
> There's a lot of "try this" in here, but no actual debugging steps. Here's how you can find the actual issue:
> 
> `zeus --log ZEUS.LOG start` then `cat ZEUS.LOG`

This is the real answer. The "exit status 1" is just a symptom of multiple possible causes. In my case, I tried logging and detected that my gem system was broken. I just did 'gem update --system' and I got zeus working again. But most likely this was just for me.

**Comment by ka8725** [comment]
Seems removing the "wrong" gem version is the only way to go, it's even in bundler official docs https://bundler.io/man/bundle-exec.1.html#RUBYGEMS-PLUGINS
