### ISSUE TITLE
zeus "can't connect to master" if run from a sub directory of rails application.

### ISSUE THREAD

**Issue by phallstrom** [burke/zeus#301]
I tend to cd around to various directories in my rails app.  If I'm in one of them and try to run any zeus command it fails with "Can't connect to master. Run zeus start first.".  I'm no go expert, but it looks like this is because zeus is coded to look for .zeus.sock in the current directory.

I wish I had a fix, but I'm not sure that crawling up the directory tree is a good idea either.  That's what Rake does though so maybe it's okay?

**Comment by ATripathy1** [comment]
I am trying to run zeus within the vagrant and I have tried many options the zeus sever starts up but. I get the following error when I run the test.

$ zeus test spec/models/llooker_spec.rb 
Can't connect to master. Run zeus start first.

vagrant 4495 3739 0 21:34 pts/0 00:00:01 /home/vagrant/.rvm/gems/ruby-2.1.5@homestars/gems/zeus-0.15.4/build/zeus-linux-amd64 start master
vagrant 4509 4495 0 21:34 pts/0 00:00:00 /home/vagrant/.rvm/gems/ruby-2.1.5@homestars/gems/zeus-0.15.4/ext/inotify-wrapper/inotify-wrapper
vagrant 4512 4495 0 21:34 pts/0 00:00:02 zeus slave: boot

vagrant 4526 4512 2 21:34 pts/0 00:00:06 zeus slave: default_bundle

vagrant 4531 4526 10 21:34 pts/0 00:00:29 zeus slave: development_environment

vagrant 4534 4526 10 21:34 pts/0 00:00:27 zeus slave: test_environment

vagrant 4572 4534 8 21:35 pts/0 00:00:19 zeus slave: test_helper

vagrant 4576 4531 0 21:35 pts/0 00:00:00 zeus slave: prerake

vagrant 4636 4239 0 21:39 pts/2 00:00:00 grep --color=auto zeus

I need some help. I have tried using ZEUSSOCK = /tmp/zeus.sock zeus start master...still the above errors show up...there is got to be a solution to this?
