### ISSUE TITLE
Warn about RAILS_ENV=env not taking effect with zeus

### ISSUE THREAD

**Issue by hakunin** [burke/zeus#391]
Hello, I love zeus, but this is something that made me mad until I realised the RAILS_ENV has no effect when running zeus rake.

````ruby
# here the RAILS_ENV is ignored and so, the DEV database is migrated
michal $ zeus rake RAILS_ENV=test db:migrate
==  AddUserIdToCart: migrating ================================================
-- add_column(:carts, :user_id, :integer, {:nil=>false})
   -> 0.0055s
-- add_index(:carts, :user_id, {:name=>"carts_user"})
   -> 0.2687s
==  AddUserIdToCart: migrated (0.2745s) =======================================

# here the RAILS_ENV is honored and so, the TEST database is migrated
michal $ rake RAILS_ENV=test db:migrate
Sass is in the process of being separated from Haml,
and will no longer be bundled at all in Haml 3.2.0.
Please install the 'sass' gem if you want to use Sass.
==  AddUserIdToCart: migrating ================================================
-- add_column(:carts, :user_id, :integer, {:nil=>false})
   -> 0.0355s
-- add_index(:carts, :user_id, {:name=>"carts_user"})
   -> 0.0081s
==  AddUserIdToCart: migrated (0.0438s) =======================================
````

It would be nice to warn about the RAILS_ENV being ignored, its something that took me a long time to realise, I thought I was typing it wrong or something..

**Comment by nocache** [comment]
in Zeus version 0.15.4 (at least)
`RAILS_ENV=test zeus rake db:migrate`
produces this:
`Warning: Specifying a Rails environment via RAILS_ENV has no effect for commands run with zeus.
As a safety precaution to protect you from nuking your development database,
Zeus will now cowardly refuse to proceed. Please unset RAILS_ENV and try again.`
