### ISSUE TITLE
Starting Zeus via non-terminal application

### ISSUE THREAD

**Issue by gnufied** [burke/zeus#431]
Zeus does weird things when starting up. For example, I was trying to write a zeus-mode for emacs. But when I start zeus via Emacs it goes in some kind of
infinite loop and endlessly prints stuff (with color coding) in Emacs buffer.

Similarly if you start zeus via `spawn` method of Ruby, zeus acts weird and prints endlessly same message over and over again.

Is there anyway this behavior can be fixed?

**Comment by sideshowcoder** [comment]
I would love to have a zeus emacs mode, currently zeus does some fancy things with the terminal output I wonder if a "simple" mode which just prints line by line what is going on would be helpful.

**Comment by sideshowcoder** [comment]
@gnufied #625 what do you think?

**Comment by sideshowcoder** [comment]
I merged #625 this includes a quick version of a emacs mode for zeus.
