### ISSUE TITLE
Cannot start Zeus - Tells to remove .zeus.sock file, but that doesn't exist

### ISSUE THREAD

**Issue by bijanrich** [burke/zeus#470]
Hello,

In my Rails directory, I'm trying to start Zeus. 

```
Starting Zeus server v0.15.1
Unable to accept socket connection.
It looks like Zeus is already running. If not, remove .zeus.sock and try again.
```

The problem is that I don't have a .zeus.sock folder. It doesn't exist anywhere. ps aux | grep zeus returns nothing. I have run zeus from this folder before without issues (though not on this machine).

Please advise.

**Comment by DevAVIJIT7** [comment]
run ls -al , if find .zeus.sock remove it using command rm .zeus.sock.

**Comment by weichenghsu** [comment]
+1 
![inline](https://i.imgur.com/xvniocy.png=300x "Title")
