### ISSUE TITLE
get signal killed every time

### ISSUE THREAD

**Issue by poc7667** [burke/zeus#508]
I have no idea what's the problem.

	% zeus start                                                                                                                                 (git)-[master]
	Starting Zeus server v0.15.4
	[ready] [crashed] [running] [connecting] [waiting]
	boot
	└── default_bundle
	    ├── development_environment
	    │   └── prerake
	    └── test_environment
	        └── test_helper

	Available Commands: [waiting] [crashed] [ready]
	zeus rake [run to see backtrace]
	zeus runner (alias: r) [run to see backtrace]
	zeus console (alias: c) [run to see backtrace]
	zeus server (alias: s) [run to see backtrace]
	zeus generate (alias: g) [run to see backtrace]
	zeus destroy (alias: d) [run to see backtrace]
	zeus dbconsole [run to see backtrace]
	zeus test (alias: rspec, testrb) [run to see backtrace]
	signal: killed

**Comment by latortuga** [comment]
Does your app run without zeus?

**Comment by poc7667** [comment]
sorry, it seems the zeus version in my Gemfile and the rbenv's default  zeus version are mismatch. pleas
e help me close this issue thanks

**Comment by ldrbrandon** [comment]
I'm actually getting this one now. I simply gem installed zeus and everything worked fine. but everytime I run zeus start, it gets the signal: killed error. This is the first line of the error:
```
```

**Comment by adeeb1** [comment]
I just had this issue, and it was because I had to install pending gems in my bundle. Make sure you can run `rails s` successfully first.

**Comment by yjaspar** [comment]
Hi, I'm actually getting the same error but I don't have any problem running my app in local.
Actually some of my coworkers use zeus on the same app, but for some reason I get signal killed at all time.

Please let me know if you need any information.
Thank you!
