### ISSUE TITLE
Bug Report: zeus test -n failure

### ISSUE THREAD

**Issue by posgarou** [burke/zeus#509]
## Description of Problem

If you run `$ zeus test -h`, it mentions the `-n` flag. Running `$zeus test -n path/to/foo_test.rb` fails with a NoMethodError.

## System details

* **`uname -a`**: Darwin _______-MacBook-Pro.local 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64

* **`ruby -v`**: ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]

## Steps to Reproduce

1) `zeus start` in a new rails project

2) Create a test file at `test/models/location_test.rb`.

3) Run `$ zeus test -n test/models/location_test.rb`.

## Observed Behavior

The following error:

```
/Users//.rvm/gems/ruby-2.2.0@posgarou-iy-cohorts/gems/zeus-0.15.4/lib/zeus/m.rb:186:in `block in parse_options!': missing argument: -n (OptionParser::MissingArgument)
	from /Users//.rvm/gems/ruby-2.2.0@posgarou-iy-cohorts/gems/zeus-0.15.4/lib/zeus/m.rb:160:in `new'
	from /Users//.rvm/gems/ruby-2.2.0@posgarou-iy-cohorts/gems/zeus-0.15.4/lib/zeus/m.rb:160:in `parse_options!'
	from /Users//.rvm/gems/ruby-2.2.0@posgarou-iy-cohorts/gems/zeus-0.15.4/lib/zeus/m.rb:132:in `parse'
```

## Expected Behavior

It should run the test at the location specified, just as `zeus test test/models/location_test.rb` does.

**Comment by latortuga** [comment]
I know it's misleading, perhaps there's something we can do to fix this, but the output from `zeus test -h` is actually the output for the `m` library. Confirm this yourself by running `m -h` if you have the m gem installed. zeus includes a copy of the gem's essential functionality and uses it for running tests by name. Hence, you don't need to use the `-n` flag, you can just run tests by name with no flags:

`zeus test test/models/location_test.rb`

Or by line number:

`zeus test test/models/location_test.rb:15`

**Comment by posgarou** [comment]
Makes sense. Thanks!
