### ISSUE TITLE
zeus assumes RAILS_ENV when none specified

### ISSUE THREAD

**Issue by SergeyBukhman** [burke/zeus#511]
When I try to generate a model using RubyMine's 'Run Rails Generator...' command, the following happens:

    /Users/sergey/.rvm/rubies/ruby-2.1.5/bin/ruby -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) /Users/sergey/.rvm/gems/ruby-2.1.5@rails4.2/bin/zeus generate model abcd -s
    Warning: Specifying a Rails environment via RAILS_ENV has no effect for commands run with zeus.
    As a safety precaution to protect you from nuking your development database,
    Zeus will now cowardly refuse to proceed. Please unset RAILS_ENV and try again.

    Process finished with exit code 1

When I run the same command manually in terminal, it works fine. I went through the 'Edit Configurations...' menu and didn't find a RAILS_ENV setting there anywhere.

![screen shot 2015-03-15 at 11 54 23 am](https://cloud.githubusercontent.com/assets/6083655/6655428/26d078f2-cb0a-11e4-856c-2e1543d5f608.png)

I think it has something to do with this dialog, as it forces to pick an environment and doesn't give the 'Default' option

**Comment by latortuga** [comment]
I sympathize with you but this is a RubyMine issue, not a zeus issue. If you can customize the command somewhere you can add something like `unset RAILS_ENV`.
