### ISSUE TITLE
Rails generators not running because of RAILS_ENV

### ISSUE THREAD

**Issue by SergeyBukhman** [burke/zeus#512]
I didn't manually set RAILS_ENV anywhere, but generators seem to default to `development` environment. Note that this **does not** happen with rake tasks, as they have a `default` environment that seems to work fine.

    /Users/sergey/.rvm/rubies/ruby-2.1.5/bin/ruby -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) /Users/sergey/.rvm/gems/ruby-2.1.5@rails4.2/bin/zeus generate migration foo
    Warning: Specifying a Rails environment via RAILS_ENV has no effect for commands run with zeus.
    As a safety precaution to protect you from nuking your development database,
    Zeus will now cowardly refuse to proceed. Please unset RAILS_ENV and try again.

    Process finished with exit code 1

**Comment by latortuga** [comment]
Is `RAILS_ENV` set in your `.profile` or similar (`.bash_profile`, `.zsh_profile`, etc)? It is obviously set otherwise you wouldn't be getting the message, the question is simply where it is set. Unset it and you'll be good to go.

**Comment by SergeyBukhman** [comment]
Hey, thanks for answering. I searched through and through and couldn't find RAILS_ENV set in any of those file (or others). I found some settings for rspec, but that's unrelated. Where else could it be? Besides, why do you think rake tasks work fine but generators do not?

**Comment by latortuga** [comment]
If you run `echo $RAILS_ENV` from the command line where the zeus call is failing, what do you see?

**Comment by SergeyBukhman** [comment]
This only happens when I use the RubyMine built in generate command Tools > Run Rails Generator. Weirdly enough, when I manually type the command `zeus generate migration foo` in terminal it works fine. Which leads me to think this might not be a zeus issue.

Still any clue as to why this happens when using the RubyMine shortcut? It's pretty convenient (Cmd+Alt+G).

**Comment by latortuga** [comment]
Probably because RubyMine sets a RAILS_ENV for its commands. If you can customize the actual command itself, you can add an `unset RAILS_ENV` to it. I'm not familiar enough with RubyMine to know if that's possible or not.

**Comment by shimaamarzouk** [comment]
I found it was set in my `~/.bash_profile` file
