### ISSUE TITLE
Zeus rake [command] loads and tries to runs the specs instead of the desired tasks.

### ISSUE THREAD

**Issue by hraynaud** [burke/zeus#515]
I'm taking over a Rails 3 project and would like to add zeus to speed things up.  Everything works fine except when I try to run zeus rake [WHATEVER].

Zeus automatically calls the default task 'spec" instead of the task I'm attempting to run (e.g. -T, jobs:work, db:test:prepare)

    /Users/herbyraynaud/.rbenv/versions/2.0.0-p643/bin/ruby -S rspec

The output is just a dump of all the specs filenames in the project. Note running the same rake commands without zeus e.g.  

    bundle exec rake -T

 works fine.

**Comment by latortuga** [comment]
This does not happen for me. What version of zeus are you on?

**Comment by hraynaud** [comment]
Hey @latortuga  thanks for the speedy repsponse. I'm on 2.0.14.

This is probably something wacky with this code base and it's configurations as quite a few of the tweaks that have been made are unconventional. 

All of my other projects work perfectly fine with zeus so It's almost certainly not zeus itself.

Opening the issue was more of long-shot to see if you'd every seen this or similar behavior before. Feel free to close. 

Thanks
