### ISSUE TITLE
Instance variables defined in test_helper lost when test suite is run

### ISSUE THREAD

**Issue by prakashmurthy** [burke/zeus#516]
Seems like I hit a weird edge case....

I modified my test suite to create a few test objects as part of the test setup with the following code in `test/test_helper.rb`:

    class ActiveSupport::TestCase
      setup :global_setup
   
      def global_setup
        @admin_user = ...
         ...
      end

With this change, when I run the tests with `zeus test test`, every test that uses the `@admin_user` variable to log into the system fails. Found that `@admin_user` has a `nil` value where it is used in the tests. Also confirmed that every other instance variable I create in the setup method is nil when invoked from the tests when `zeus test test` is used.

The test suite successfully completes when I run `rake test`. Also, running tests in a single file or folder with `zeus` works fine as well. All of the following commands work as expected:

    zeus test test/controllers/users_controller_test.rb
    zeus test test/models/
    zeus test test/controllers/admin/users_controller_test.rb:33

This is with rails `4.2.0` and zeus `0.15.4`

**Comment by latortuga** [comment]
Unfortunately this doesn't happen for me. If you provide an example app that this happens reliably for I can investigate further.

**Comment by prakashmurthy** [comment]
Thanks @latortuga for responding. I will try to debug further later on. Since I am able to run the full suite with `rake test` and specific tests with `zeus test test/...`, this is not a blocking issue for me right now.
