### ISSUE TITLE
SIGINFO is not passed through

### ISSUE THREAD

**Issue by russelldavis** [burke/zeus#518]
When running a minitest test suite, you can normally press Ctrl-T to send SIGINFO, which minitest will respond to by printing out the current state. When running via zeus, the signal does not get passed through,.

**Comment by latortuga** [comment]
Unfortunately I develop on Ubuntu where SIGINFO is not supported so it will be difficult for me to resolve this one. I could make an RC build to see if my changes fix it for OS X...

**Comment by russelldavis** [comment]
Thanks, if you're up for it, I'd be more than happy to test out an RC build.

**Comment by russelldavis** [comment]
Closing out old issues I've filed that have gone inactive.
