### ISSUE TITLE
zeus wont restart after rails routes updates

### ISSUE THREAD

**Issue by RunsFor** [burke/zeus#521]
Hi.

Thanks everyone who supporting this useful project. It saves time in development process!

I'm running into some issues with restarting zeus after code changes, and since I'm not deeply understand how zeus works, I'm asking you for help.

I've splitted my `config/routes.rb` using this [hack](http://blog.arkency.com/2015/02/how-to-split-routes-dot-rb-into-smaller-parts/) by defining `draw` method. And than, after I update file, which was included in `routes.rb`, my routing spec results doesn't change. Only explicitly saving `routes.rb` file helps.

I understand that this might not be zeus issue, but maybe smbd has advises how to fix it.

**Comment by latortuga** [comment]
Thanks for the kind words!

As for the linked blog post,`instance_eval` ick! Seems like the simple solution would be to use `require`:

```ruby
YourApplication::Application.routes.draw do
  root to: "home#index"
  get "/about
  get "/login" => "application#login" 
end

ADDITIONAL_ROUTES = [:messages, :orders, :api, :admin]
ADDITIONAL_ROUTES.each do |route_file|
  require "config/routes/#{routes_file}"
end
```

This way you can load them at whatever point you actually need them, before, in the middle, after, etc. As far as I know, there's no problem calling `Application.routes.draw` multiple times.

In fact, I tested this exact approach just now on a Rails 4.1 app and it worked flawlessly, reloading zeus automatically on changes to routes or config/routes/*.rb files.

**Comment by krisleech** [comment]
or `require_relative 'routes/admin'`

**Comment by wayne5540** [comment]
Another way to split routes file could be using `extend`, not sure if reloading works with zeus or not, however it works for me without zeus.

Example:

In `config/routes.rb`

```rb
Rails.application.routes.draw do
  root to: "home#index"
  
  extend AdminRoutes
end
```

In `config/routes/admin_routes.rb`

```rb
module AdminRoutes
  def self.extended(router)
    router.instance_exec do
      namespace :admin do
        resources :posts
      end
    end
  end
end
```

In `config/application.rb`

```rb
module Platform
  class Application < Rails::Application
    # ...
    config.autoload_paths += Dir.glob("#{config.root}/config/routes")
    # ...
  end
end
```
