### ISSUE TITLE
Zeus: Unable to accept socket connection. Long run

### ISSUE THREAD

**Issue by dominch** [burke/zeus#522]
Hello 
I wanted to run Zeus with small and fast task (fetching e-mail for redmine) 
Task run without zeus is about 15s, and with zeus less than 1s :)
It works. I got: 
<pre>
www-data@avazar3:~/ruby/redmine$ zeus start
Starting Zeus server v0.15.4
[ready] [crashed] [running] [connecting] [waiting]
boot
└── default_bundle
    ├── development_environment
    │   └── prerake
    └── test_environment
        └── test_helper

Available Commands: [waiting] [crashed] [ready]
zeus rake
zeus runner (alias: r)
zeus console (alias: c)
zeus server (alias: s)
zeus generate (alias: g)
zeus destroy (alias: d)
zeus dbconsole
zeus test (alias: rspec, testrb) [run to see backtrace]
</pre>
Cron invoke zeus rake... every minute. 
Everyting is ok. I'm leaving this in terminal and later I can find red
<pre>
Unable to accept socket connection.
Unable to accept socket connection.
Unable to accept socket connection.
Unable to accept socket connection.
Unable to accept socket connection.
Unable to accept socket connection.
Unable to accept socket connection.
Unable to accept socket connection.
Unable to accept socket connection.
Unable to accept socket connection.
Unable to accept socket connection.
Unable to accept socket connection.
Unable to accept socket connection.
Unable to accept socket connection.
Unable to accept socket connection.
Unable to accept socket connection.
Unable to accept socket connection.
Unable to accept socket connection.
Unable to accept socket connection.
Unable to accept socket connection.
Unable to accept socket connection.
Unable to accept socket connection.
Unable to accept socket connection.
Unable to accept socket connection.
Unable to accept socket connection.
Unable to accept socket connection.
Unable to accept socket connection.
Unable to accept socket connection.
Unable to accept socket connection.
Unable to accept socket connection.
Unable to accept socket connection.
</pre>
Tasks are not working. Restarting zeus helps and I can again leave it for some time. 
Any idea why it stops to work? 
I don't know how long it is running, in logs I found: 
<pre>
Tue May 26 11:12:01 CDT 2015
zeusclient.go:95: .[31mEOF
.[0m
Tue May 26 11:13:01 CDT 2015
zeusclient.go:221: .[31mCould not send arguments across: write socketpair-a: broken pipe
.[0m
zeusclient.go:95: .[31mEOF
.[0m
Tue May 26 11:14:01 CDT 2015
zeusclient.go:95: .[31mEOF
.[0m
Tue May 26 11:15:02 CDT 2015
zeusclient.go:95: .[31mEOF
.[0m
</pre>

**Comment by latortuga** [comment]
Zeus is designed to be a tool for development, not production. If you want something to keep your processes alive in production, check out init or god or any number of other process management tools.

**Comment by dominch** [comment]
I don't need monitoring, rather something to preload ruby and rails. Loading ruby every minute will dump memory of VM :( 
Zeus works here with redmine, except that message after some time. 
Anything else like zeus that can be used in production?

**Comment by latortuga** [comment]
You want a long-running process outside your server process. The usual tool for this job is to run a job worker like Resque, Delayed Job, or Sidekiq. Cron obviously works well but you do have the problem that you have to load the app every time the cron job runs.

The kernel is probably killing the processes because they mostly just sit there idle. Zeus is just not designed for this use case, sorry.

**Comment by dominch** [comment]
Also Spring is not designed to run on production, but both zeus and spring are top results in google when You looking for rails preloader. 
Eventually I found ruby cron-like solution that is running background process and keeps in memory whatever it needs, I needed to add code from rake to it but now it's working. 
Thanks for Your support :)
