### ISSUE TITLE
Zeus Debugging

### ISSUE THREAD

**Issue by dalizard** [burke/zeus#529]
I am running OSX 10.11, ruby 2.2.2p95 and zeus 0.15.4. The installation of the gem went without a problem, however running `zeus start` simply returns *exit status 1* right away:
![screen shot 2015-10-02 at 5 00 04 pm](https://cloud.githubusercontent.com/assets/148763/10248287/24d8de16-6927-11e5-89f1-df655c359db4.png)
There are no logs, I can't see any way to print out verbose messages either. How do you debug the code when it doesn't work?

**Comment by kgrz** [comment]
@dalizard One way to do this is to use tools like `strace` (Linux) and `dtruss`(OSX specific). On a mac, you'd run `sudo dtruss -n zeus` in a terminal window, and `zeus start` in another window.

**Comment by dalizard** [comment]
@kgrz Thank you -- I've fixed the problem. However, I think it would be helpful if we got some verbose output in case of a failure.
