### ISSUE TITLE
Where is the 'zeus/version' file located?

### ISSUE THREAD

**Issue by kgrz** [burke/zeus#531]
I've noticed that [this line] throws an error when I run `bundle exec rspec`  in my local fork. I tried to find out where this is located, but failed. Can the line be removed?

[this line]: https://github.com/burke/zeus/blob/master/rubygem/lib/zeus.rb#L15

**Comment by latortuga** [comment]
The project Makefile has tasks to generate the version files. There are actually multiple tasks for this:

```sh
make go/zeusversion/zeusversion.go
make rubygem/lib/zeus/version.rb
make vagrant/lib/vagrant-zeus/version.rb
```

Generally when I'm testing a build, I populate the VERSION file with a testing build number (e.g. 0.15.5.rc1) and then generate the version files.
