### ISSUE TITLE
zeus console loads pry instead of irb

### ISSUE THREAD

**Issue by flynfish** [burke/zeus#533]
## zeus console loads pry instead of irb

when running `zeus c`, it loads pry console by default, instead of irb console. Is there a way to load `irb` by default instead of `pry`?

## System details

* **`uname -a`**: 
`Linux dev 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:08:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

* **`ruby -v`**: 
`ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]`

## Steps to Reproduce

1) Ensure you have pry gem installed

2)`zeus console` in a new rails project

## Observed Behavior

* `[1] pry(main)>`

## Expected Behavior

* 
```
Loading development environment (Rails 3.2.19)
cfs-web(dev)>
```

**Comment by latortuga** [comment]
Option 1: Remove pry from your Gemfile.
Option 2: Add `require: false` to pry in your Gemfile.
