### ISSUE TITLE
Version 0.15.8 not available on Rubygems

### ISSUE THREAD

**Issue by keithpitty** [burke/zeus#563]
The latest version available on Rubygems is 0.15.4. Why are more current versions not available?

**Comment by burke** [comment]
I can probably publish a release early next week.

**Comment by lonre** [comment]
👍

**Comment by burke** [comment]
Whoops, forgot about this. Pushed 0.15.8 just now.

**Comment by longkt90** [comment]
Do you know why the version doesn;t  appear in https://rubygems.org/gems/zeus/ ? The latest is still 0.15.4 from January 21, 2015.

Only have a lot of hidden versions here https://rubygems.org/gems/zeus/versions And I cannot install zeus through ` gem install zeus -v '1.13.0.preview1' --source http://rubygems.org`

Maybe you should double check about publishing it?

**Comment by burke** [comment]
That build crashed on startup for most people, so I yanked it. Someone pushed 0.15.9 I think, but it had a similar issue. Not sure what the status is now.

**Comment by metcalf** [comment]
I have a proposed fix in https://github.com/burke/zeus/issues/570 and am awaiting some feedback. Sorry for the delay in getting something out!

**Comment by metcalf** [comment]
Released 0.15.10 with a fix for #570. Please report any fresh issues!
