### ISSUE TITLE
Compatibility with Rails 5

### ISSUE THREAD

**Issue by rattrayalex** [burke/zeus#569]
Rails 5 was just released. Is zeus compatible?

If not, perhaps this issue can serve as a tracker for work that needs to be done to get there.

**Comment by latortuga** [comment]
I have been using zeus with Rails 5 beta and rc releases for months, should be fine.

**Comment by TangMonk** [comment]
rails 5.1.1 not works

**Comment by jujudellago** [comment]
Any evolution on the topic ? If zeus development stopped, can anyone recommend an alternative for rails 5 ?

**Comment by TangMonk** [comment]
@rails5 integrate spring native and better than rails 5, you can fast execute command without zeus
