### ISSUE TITLE
Rspec requires path with latest release

### ISSUE THREAD

**Issue by typeoneerror** [burke/zeus#582]
Since 0.15.10, I now have to specify a path to run rspec

```
zeus rspec spec/
```

Otherwise, "All examples were filtered out".

Previously (and without zeus), I could run:

```
zeus rspec
```

Is this an API change with latest? Is this configurable? This may be an rspec configuration issue, but wanted to report to make sure. Thank you!

> Darwin 13.4.0 Darwin Kernel Version 13.4.0: Mon Jan 11 18:17:34 PST 2016; root:xnu-2422.115.15~1/RELEASE_X86_64 x86_64
> ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin13]

**Comment by metcalf** [comment]
@typeoneerror: what version of Zeus were you using before you observed this problem?

This seems like a plausible candidate for the regression: https://github.com/burke/zeus/pull/497/files
cc @sshao

**Comment by typeoneerror** [comment]
@metcalf unsure, but from the looks of it, I'm guessing it was this change here 

https://github.com/burke/zeus/commit/954894af8c1d69af958860ea7f2bd2333283b91f

Looks like this removed the addition of "spec" as path if it didn't exist. Perhaps I should look into the RSpec "autorunner" referenced in the commit to use that instead?

**Comment by metcalf** [comment]
Ah, that makes sense. We don't use rspec (nor the Zeus test runner code at all) so I'm not sure what standard practice is. Mind investigating the autorunner for your use case?

Regardless of whether it's standard, I don't love that this introduced a regression so I think we should leave this issue open for the moment in case others encounter it. 

cc @latortuga from https://github.com/burke/zeus/pull/514

**Comment by sideshowcoder** [comment]
Should be fixed with #622
