### ISSUE TITLE
Zeus 0.15.10 no test examples found

### ISSUE THREAD

**Issue by J-ad** [burke/zeus#595]
## Description of Problem

Just installed zeus 0.15.10, all zeus commands work fine but no test examples are found. Downgrading to 0.15.4 fixed the issue.  
## System details
- **`ruby -v`**:
  ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15] 

Test framework: 
Rspec
## Steps to Reproduce

1) `zeus start` in a new rails project

2) `zeus rspec`
## Observed Behavior
- no test examples found
## Downgrade to 0.15.4
- zeus finds all test examples

**Comment by metcalf** [comment]
@latortuga: It seems plausible that this is related to #588 which in turn appears to stem from your #514. Mind checking if any work you do on #588 also resolves this?

**Comment by eagleeye2020** [comment]
I worked around it by adding the dir /spec to the command

zeus test /spec

Zeus invokes Rspec
RSpec::Core::Runner.invoke

And Rspec expects ARGV to contain the dir path to run.
status = run(ARGV, $stderr, $stdout).to_i

which calls

line 64: rspec-core-3.5.4/lib/rspec/core/runner.rb
def self.run(args, err=$stderr, out=$stdout)

and configures what dir to run for tests.

So Rspec expects the test dir to be explicitly set in the arguments when being invoked.

**Comment by sideshowcoder** [comment]
See the linked PR which restores the 0.15.4 behaviour. As I'm not an avid rspec user I'm not sure this is what we really want @J-ad @nathantech2005 I guess this basically copies what `bundle exec rspec` would do so right?
