### ISSUE TITLE
fatal error: MSpanList_Insert 

### ISSUE THREAD

**Issue by prakash-subramani** [burke/zeus#608]
Im using Mac sierra. While running my rails application with zeus its breaks frequently with following error 

`failed MSpanList_Insert`

`failed MSpanList_Insert 0x3ab4d0 0x3b2a5acb200 0x0
fatal error: MSpanList_Insert

goroutine 7 [running] :
    runtime.throw(0x2e7b2c)
/usr/ local/go/src/pkg/runtime/panic.c : 464 +0x69 fp=0x781ca8
runtime.MSpanList_Insert(0x2fde58, 0x3ab4d0)
/usr/ local/go/src/pkg/runtime/mheap.c : 544 +0x8a fp=0x781cd0
MHeap_FreeLocked(0x2fd3c0, 0x3ab4d0)
/usr/ local/go/src/pkg/runtime/mheap.c : 377 +0x12a fp=0x781d18
MHeap_AllocLocked(0x2fd3c0, 0x1, 0x1d)
/usr/ local/go/src/pkg/runtime/mheap.c : 178 +0x228 fp=0x781d58
runtime.MHeap_Alloc(0x2fd3c0, 0x1, 0x1d, 0x1)
/usr/ local/go/src/pkg/runtime/mheap.c : 95 +0x7b fp=0x781d80
MCentral_Grow(0x305e00)
/usr/ local/go/src/pkg/runtime/mcentral.c : 180 +0x8c fp=0x781de0
runtime.MCentral_AllocList(0x305e00, 0x3a41e0)
/usr/ local/go/src/pkg/runtime/mcentral.c : 46 +0x4f fp=0x781e08
runtime.MCache_Refill(0x3a4000, 0x1d)
/usr/ local/go/src/pkg/runtime/mcache.c : 22 +0x7c fp=0x781e28
runtime.mallocgc(0x400, 0x102fc1, 0x1)
/private/ var/folders/00/0 sdwh000h01000cxqpysvccm0035qk/T/makerelease260794574/go/src/pkg/runtime/malloc.goc : 71 +0xff fp=0x781e98
cnew(0x102fc0, 0x400, 0xc200000001)
/private/ var/folders/00/0 sdwh000h01000cxqpysvccm0035qk/T/makerelease260794574/go/src/pkg/runtime/malloc.goc : 718 +0xc1 fp=0x781eb8
runtime.cnewarray(0x102fc0, 0x400)
/private/ var/folders/00/0 sdwh000h01000cxqpysvccm0035qk/T/makerelease260794574/go/src/pkg/runtime/malloc.goc : 731 +0x3a fp=0x781ed8
makeslice1(0xfaf40, 0x400, 0x400, 0x781f38)
/usr/ local/go/src/pkg/runtime/slice.c : 57 +0x4d fp=0x781ef0
runtime.makeslice(0xfaf40, 0x400, 0x400, 0x400, 0x400, ...)
/usr/ local/go/src/pkg/runtime/slice.c : 38 +0x98 fp=0x781f20
github.com/burke/zeus/go/zeusclient.func · 003()
/Users/ni ck/Work/gopath/src/github.com/burke/zeus/go/zeusclient/zeusclient.go : 146 +0x4a fp=0x781fa0
runtime.goexit()
/usr/ local/go/src/pkg/runtime/proc.c : 1394 fp=0x781fa8
created by github.com/burke/zeus/go/zeusclient.doRun
/Users/ni ck/Work/gopath/src/github.com/burke/zeus/go/zeusclient/zeusclient.go : 154 +0xb5d

goroutine 1 [chan receive] :
    github.com/burke/zeus/go/zeusclient.doRun(0x0)
/Users/ni ck/Work/gopath/src/github.com/burke/zeus/go/zeusclient/zeusclient.go : 181 +0xbc1
github.com/burke/zeus/go/zeusclient.Run()
/Users/ni ck/Work/gopath/src/github.com/burke/zeus/go/zeusclient/zeusclient.go : 27 +0x1e
main.main()
/Users/ni ck/Work/gopath/src/github.com/burke/zeus/go/cmd/zeus/zeus.go : 74 +0x5c4

goroutine 3 [syscall] :
    os/signal.loop()
/usr/ local/go/src/pkg/os/signal/signal_unix.go : 21 +0x1e
created by os/signal.init · 1
/usr/ local/go/src/pkg/os/signal/signal_unix.go : 27 +0x31

goroutine 4 [finalizer wait] :
    runtime.park(0xd3c0, 0x2eaf78, 0x2e9dc8)
/usr/ local/go/src/pkg/runtime/proc.c : 1342 +0x66
runfinq()
/usr/ local/go/src/pkg/runtime/mgc0.c : 2279 +0x84
runtime.goexit()
/usr/ local/go/src/pkg/runtime/proc.c : 1394

goroutine 6 [chan receive] :
    github.com/burke/zeus/go/zeusclient.func · 002()
/Users/ni ck/Work/gopath/src/github.com/burke/zeus/go/zeusclient/zeusclient.go : 118 +0x57
created by github.com/burke/zeus/go/zeusclient.doRun
/Users/ni ck/Work/gopath/src/github.com/burke/zeus/go/zeusclient/zeusclient.go : 131 +0xa22

goroutine 8 [syscall] :
    syscall.Syscall(0x3, 0x0, 0xc210075000, 0x2000, 0x20e79, ...)
/usr/ local/go/src/pkg/syscall/asm_darwin_amd64.s : 17 +0x5
syscall.read(0x0, 0xc210075000, 0x2000, 0x2000, 0x0, ...)
/usr/ local/go/src/pkg/syscall/zsyscall_darwin_amd64.go : 900 +0x72
syscall.Read(0x0, 0xc210075000, 0x2000, 0x2000, 0x1, ...)
/usr/ local/go/src/pkg/syscall/syscall_unix.go : 135 +0x5c
os.(*File).read(0xc210000000, 0xc210075000, 0x2000, 0x2000, 0x1e2f8, ...)
/usr/ local/go/src/pkg/os/file_unix.go : 180 +0x62
os.(*File).Read(0xc210000000, 0xc210075000, 0x2000, 0x2000, 0x2000, ...)
/usr/ local/go/src/pkg/os/file.go : 95 +0x98
github.com/burke/zeus/go/zeusclient.func · 004()
/Users/ni ck/Work/gopath/src/github.com/burke/zeus/go/zeusclient/zeusclient.go : 159 +0xb1
created by github.com/burke/zeus/go/zeusclient.doRun
/Users/ni ck/Work/gopath/src/github.com/burke/zeus/go/zeusclient/zeusclient.go : 179 +0xba5`

i don't have any idea where it comes from... while running server without zeus, it works fine

**Comment by seanpcoyle** [comment]
I'm seeing the same thing on Sierra. 

`failed MSpanList_Insert 0x3a9790 0x22527c9c1e1e1 0x0

fatal error: MSpanList_Insert

goroutine 5 [running]:
runtime.throw(0x2e7b4c)
	/usr/local/go/src/pkg/runtime/panic.c:464 +0x69 fp=0x67bca8
runtime.MSpanList_Insert(0x3002a0, 0x3a9790)
	/usr/local/go/src/pkg/runtime/mheap.c:544 +0x8a fp=0x67bcd0
MHeap_FreeLocked(0x2fd3e0, 0x3a9790)
	/usr/local/go/src/pkg/runtime/mheap.c:377 +0x12a fp=0x67bd18
MHeap_AllocLocked(0x2fd3e0, 0x1, 0x1d)
	/usr/local/go/src/pkg/runtime/mheap.c:178 +0x228 fp=0x67bd58
runtime.MHeap_Alloc(0x2fd3e0, 0x1, 0x1d, 0x1)
	/usr/local/go/src/pkg/runtime/mheap.c:95 +0x7b fp=0x67bd80
MCentral_Grow(0x305e20)
	/usr/local/go/src/pkg/runtime/mcentral.c:180 +0x8c fp=0x67bde0
runtime.MCentral_AllocList(0x305e20, 0x3a41e0)
	/usr/local/go/src/pkg/runtime/mcentral.c:46 +0x4f fp=0x67be08
runtime.MCache_Refill(0x3a4000, 0x1d)
	/usr/local/go/src/pkg/runtime/mcache.c:22 +0x7c fp=0x67be28
runtime.mallocgc(0x400, 0x103261, 0x1)
	/private/var/folders/00/0sdwh000h01000cxqpysvccm0035qk/T/makerelease260794574/go/src/pkg/runtime/malloc.goc:71 +0xff fp=0x67be98
cnew(0x103260, 0x400, 0xc200000001)
	/private/var/folders/00/0sdwh000h01000cxqpysvccm0035qk/T/makerelease260794574/go/src/pkg/runtime/malloc.goc:718 +0xc1 fp=0x67beb8
runtime.cnewarray(0x103260, 0x400)
	/private/var/folders/00/0sdwh000h01000cxqpysvccm0035qk/T/makerelease260794574/go/src/pkg/runtime/malloc.goc:731 +0x3a fp=0x67bed8
makeslice1(0xfb1e0, 0x400, 0x400, 0x67bf38)
	/usr/local/go/src/pkg/runtime/slice.c:57 +0x4d fp=0x67bef0
runtime.makeslice(0xfb1e0, 0x400, 0x400, 0x400, 0x400, ...)
	/usr/local/go/src/pkg/runtime/slice.c:38 +0x98 fp=0x67bf20
github.com/burke/zeus/go/zeusclient.func·003()
	/Users/nick/Work/gopath/src/github.com/burke/zeus/go/zeusclient/zeusclient.go:146 +0x4a fp=0x67bfa0
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1394 fp=0x67bfa8
created by github.com/burke/zeus/go/zeusclient.doRun
	/Users/nick/Work/gopath/src/github.com/burke/zeus/go/zeusclient/zeusclient.go:154 +0xb5d

goroutine 1 [chan receive]:
github.com/burke/zeus/go/zeusclient.doRun(0x0)
	/Users/nick/Work/gopath/src/github.com/burke/zeus/go/zeusclient/zeusclient.go:181 +0xbc1
github.com/burke/zeus/go/zeusclient.Run()
	/Users/nick/Work/gopath/src/github.com/burke/zeus/go/zeusclient/zeusclient.go:27 +0x1e
main.main()
	/Users/nick/Work/gopath/src/github.com/burke/zeus/go/cmd/zeus/zeus.go:86 +0x713

goroutine 3 [syscall]:
os/signal.loop()
	/usr/local/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
	/usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x31

goroutine 6 [syscall]:
syscall.Syscall(0x3, 0x0, 0xc210073000, 0x2000, 0x21349, ...)
	/usr/local/go/src/pkg/syscall/asm_darwin_amd64.s:17 +0x5
syscall.read(0x0, 0xc210073000, 0x2000, 0x2000, 0x0, ...)
	/usr/local/go/src/pkg/syscall/zsyscall_darwin_amd64.go:900 +0x72
syscall.Read(0x0, 0xc210073000, 0x2000, 0x2000, 0x1, ...)
	/usr/local/go/src/pkg/syscall/syscall_unix.go:135 +0x5c
os.(*File).read(0xc210000000, 0xc210073000, 0x2000, 0x2000, 0x1e6f8, ...)
	/usr/local/go/src/pkg/os/file_unix.go:180 +0x62
os.(*File).Read(0xc210000000, 0xc210073000, 0x2000, 0x2000, 0x2000, ...)
	/usr/local/go/src/pkg/os/file.go:95 +0x98

github.com/burke/zeus/go/zeusclient.func·004()
	/Users/nick/Work/gopath/src/github.com/burke/zeus/go/zeusclient/zeusclient.go:159 +0xb1
created by github.com/burke/zeus/go/zeusclient.doRun
	/Users/nick/Work/gopath/src/github.com/burke/zeus/go/zeusclient/zeusclient.go:179 +0xba5

goroutine 7 [finalizer wait]:
runtime.park(0xd7c0, 0x2eaf98, 0x2e9de8)
	/usr/local/go/src/pkg/runtime/proc.c:1342 +0x66
runfinq()
	/usr/local/go/src/pkg/runtime/mgc0.c:2279 +0x84
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1394`

**Comment by seanpcoyle** [comment]
I'm seeing the same thing on Sierra:

failed MSpanList_Insert 0x3a9790 0x22527c9c1e1e1 0x0

fatal error: MSpanList_Insert

goroutine 5 [running]:
runtime.throw(0x2e7b4c)
	/usr/local/go/src/pkg/runtime/panic.c:464 +0x69 fp=0x67bca8
runtime.MSpanList_Insert(0x3002a0, 0x3a9790)
	/usr/local/go/src/pkg/runtime/mheap.c:544 +0x8a fp=0x67bcd0
MHeap_FreeLocked(0x2fd3e0, 0x3a9790)
	/usr/local/go/src/pkg/runtime/mheap.c:377 +0x12a fp=0x67bd18
MHeap_AllocLocked(0x2fd3e0, 0x1, 0x1d)
	/usr/local/go/src/pkg/runtime/mheap.c:178 +0x228 fp=0x67bd58
runtime.MHeap_Alloc(0x2fd3e0, 0x1, 0x1d, 0x1)
	/usr/local/go/src/pkg/runtime/mheap.c:95 +0x7b fp=0x67bd80
MCentral_Grow(0x305e20)
	/usr/local/go/src/pkg/runtime/mcentral.c:180 +0x8c fp=0x67bde0
runtime.MCentral_AllocList(0x305e20, 0x3a41e0)
	/usr/local/go/src/pkg/runtime/mcentral.c:46 +0x4f fp=0x67be08
runtime.MCache_Refill(0x3a4000, 0x1d)
	/usr/local/go/src/pkg/runtime/mcache.c:22 +0x7c fp=0x67be28
runtime.mallocgc(0x400, 0x103261, 0x1)
	/private/var/folders/00/0sdwh000h01000cxqpysvccm0035qk/T/makerelease260794574/go/src/pkg/runtime/malloc.goc:71 +0xff fp=0x67be98
cnew(0x103260, 0x400, 0xc200000001)
	/private/var/folders/00/0sdwh000h01000cxqpysvccm0035qk/T/makerelease260794574/go/src/pkg/runtime/malloc.goc:718 +0xc1 fp=0x67beb8
runtime.cnewarray(0x103260, 0x400)
	/private/var/folders/00/0sdwh000h01000cxqpysvccm0035qk/T/makerelease260794574/go/src/pkg/runtime/malloc.goc:731 +0x3a fp=0x67bed8
makeslice1(0xfb1e0, 0x400, 0x400, 0x67bf38)
	/usr/local/go/src/pkg/runtime/slice.c:57 +0x4d fp=0x67bef0
runtime.makeslice(0xfb1e0, 0x400, 0x400, 0x400, 0x400, ...)
	/usr/local/go/src/pkg/runtime/slice.c:38 +0x98 fp=0x67bf20
github.com/burke/zeus/go/zeusclient.func·003()
	/Users/nick/Work/gopath/src/github.com/burke/zeus/go/zeusclient/zeusclient.go:146 +0x4a fp=0x67bfa0
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1394 fp=0x67bfa8
created by github.com/burke/zeus/go/zeusclient.doRun
	/Users/nick/Work/gopath/src/github.com/burke/zeus/go/zeusclient/zeusclient.go:154 +0xb5d

goroutine 1 [chan receive]:
github.com/burke/zeus/go/zeusclient.doRun(0x0)
	/Users/nick/Work/gopath/src/github.com/burke/zeus/go/zeusclient/zeusclient.go:181 +0xbc1
github.com/burke/zeus/go/zeusclient.Run()
	/Users/nick/Work/gopath/src/github.com/burke/zeus/go/zeusclient/zeusclient.go:27 +0x1e
main.main()
	/Users/nick/Work/gopath/src/github.com/burke/zeus/go/cmd/zeus/zeus.go:86 +0x713

goroutine 3 [syscall]:
os/signal.loop()
	/usr/local/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
	/usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x31

goroutine 6 [syscall]:
syscall.Syscall(0x3, 0x0, 0xc210073000, 0x2000, 0x21349, ...)
	/usr/local/go/src/pkg/syscall/asm_darwin_amd64.s:17 +0x5
syscall.read(0x0, 0xc210073000, 0x2000, 0x2000, 0x0, ...)
	/usr/local/go/src/pkg/syscall/zsyscall_darwin_amd64.go:900 +0x72
syscall.Read(0x0, 0xc210073000, 0x2000, 0x2000, 0x1, ...)
	/usr/local/go/src/pkg/syscall/syscall_unix.go:135 +0x5c
os.(*File).read(0xc210000000, 0xc210073000, 0x2000, 0x2000, 0x1e6f8, ...)
	/usr/local/go/src/pkg/os/file_unix.go:180 +0x62
os.(*File).Read(0xc210000000, 0xc210073000, 0x2000, 0x2000, 0x2000, ...)
	/usr/local/go/src/pkg/os/file.go:95 +0x98

github.com/burke/zeus/go/zeusclient.func·004()
	/Users/nick/Work/gopath/src/github.com/burke/zeus/go/zeusclient/zeusclient.go:159 +0xb1
created by github.com/burke/zeus/go/zeusclient.doRun
	/Users/nick/Work/gopath/src/github.com/burke/zeus/go/zeusclient/zeusclient.go:179 +0xba5

goroutine 7 [finalizer wait]:
runtime.park(0xd7c0, 0x2eaf98, 0x2e9de8)
	/usr/local/go/src/pkg/runtime/proc.c:1342 +0x66
runfinq()
	/usr/local/go/src/pkg/runtime/mgc0.c:2279 +0x84
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1394

**Comment by ahs8w** [comment]
+1

**Comment by smtlaissezfaire** [comment]
same here

**Comment by smtlaissezfaire** [comment]
FYI I'm running zeus-0.15.4, I'll try upgrading to the latest.

**Comment by Ninigi** [comment]
I was running into the same problem, updating to version 0.15.10 seems to have solved the issue. Since I saw a similar issue in various github repos, it seems to be a problem with the golang version? Anyways, updating the version got rid of the  issue for me.

**Comment by sideshowcoder** [comment]
It seems to work fine on my work machine (local one is linux and works fine as well) as 0.15.10 seems to fix this issue I'm gonna close this, feel free to reopen when need be.
