### ISSUE TITLE
Release 0.15.11 to RubyGems

### ISSUE THREAD

**Issue by thedrow** [burke/zeus#611]
Currently the release is not tagged. Can we please tag and release it?

**Comment by sideshowcoder** [comment]
That would be really nice, according to rubygems @burke @metcalf @turadg @antifuchs and @latortuga have access to release a new version I would like to get #614 and #615 in if at all possible. I have push commit bit but not rubygems access.

**Comment by burke** [comment]
I haven't built it in a while, I can add you as a rubygems contributor, let me know what email address you use there or link me to your profile.

**Comment by sideshowcoder** [comment]
That would be awesome @burke my rubygems profile is https://rubygems.org/profiles/sideshowcoder I'm using zeus quite a lot at work so happy to try to look after it a little :+1:

**Comment by burke** [comment]
Done :+1: Thanks!

**Comment by sideshowcoder** [comment]
Just so I don't mess this up, the build needs to be done on OSX to include all the binaries I suppose, otherwise only the linux binary are included in the release. Just realised this, as I took a look at the Makefile, will build at work on my Mac now for the release :+1:

**Comment by sideshowcoder** [comment]
Version 0.15.11 has just been released, I'm gonna close this now

**Comment by sideshowcoder** [comment]
Seems like something went wrong with the build, it didn't include the MacVersion even so I built on a mac... odd, I'm gonna yank it and try again sorry about that.

**Comment by sideshowcoder** [comment]
ok released again as 0.15.12... this time the build seems to have done fine, not sure what was going on here, the first build failed to include the binaries for linux and mac. I yanked it and released 0.15.12. Hope all is well now, I tested a local install and it seems fine.
