### ISSUE TITLE
Log "can't connect to master" into the STDERR

### ISSUE THREAD

**Issue by bogdan** [burke/zeus#612]
When the zeus server is not started. the following command:

```
$ zeus rake routes | grep <something>
```

Produces no output as if there is just no such route defined, but it is just because server is not started.

Please put `Can't connect to master. Run zeus start first.` into STDERR so that it is always displayed in spite of `grep`.

**Comment by sideshowcoder** [comment]
This is related to #336 currently there is only one stream for stderr and stdout. Something I wanted to tackle some time ago, got distracted, forgot and now annoys me again...

**Comment by bogdan** [comment]
Maybe this is not related as the problem here occurs in zeus code not in the environment made by zeus for ruby.

**Comment by sideshowcoder** [comment]
Oh yes I missunderstood what you ment sorry about this, I created a quick PR #614  to fix this and I'm wondering if there are more errors which should be logged to stderr now created by zeus.
