### ISSUE TITLE
Contributing help: govendor: command not found

### ISSUE THREAD

**Issue by typeoneerror** [burke/zeus#628]
I'm following along with contributing.md and when I get to step 3 I end up with:

```
~/go/src/github.com/burke/zeus (master) $ make
mkdir -p go/zeusversion
mkdir -p rubygem/lib/zeus
go get github.com/kardianos/govendor
ZEUS_TEST_GEMPATH="/Users/typeoneerror/go/src/github.com/burke/zeus/rubygem" GO15VENDOREXPERIMENT=1 govendor test +local
/bin/sh: govendor: command not found
make: *** [test-go] Error 127
```

Darwin t1e.local 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64

ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]

go version go1.8 darwin/amd64

**Comment by typeoneerror** [comment]
Ah, I see what happened. I only set $GOPATH and neglected to add $GOPATH/bin to my $PATH.

**Comment by sideshowcoder** [comment]
👍

**Comment by chenxi-vmware** [comment]
Cool.
