### ISSUE TITLE
"Terminated: 15 " Running tests

### ISSUE THREAD

**Issue by jeremiahlukus** [burke/zeus#631]
While running zeus rspec I get this error. If I run it again everything works fine. Half of the time it works normally. The other half I get Terminated: 15 then it works after running again.

**Comment by jeremiahlukus** [comment]
Now it just randomly stopped working?

**Comment by laughinghan** [comment]
Dupe of https://github.com/burke/zeus/issues/598

**Comment by sideshowcoder** [comment]
As dupe of #598 going to close that.
