### ISSUE TITLE
zeus and pry don't play nice

### ISSUE THREAD

**Issue by sfahlberg** [burke/zeus#632]
Hi there,
I love Zeus! Although the only issue is that when I'm running pry I end up having issues with scrolling and I can no longer scroll down. Any solutions for this issue?

**Comment by sideshowcoder** [comment]
This is a know issue and I'm currently investigating what is going on see #627 and #633

**Comment by sideshowcoder** [comment]
I just merged a change to deactivate paging in pry for now, the problem seems to be that pry and zeus don't forward stdin / stderr correctly to an external pager for some reason. Iḿ building a new version now.

**Comment by yijia-zhan** [comment]
any updates on this?

**Comment by vegajdr** [comment]
@yijia-zhan I tried switching from `NullPager` to `SimplePager` in `rubygem/lib/zeus/pry.rb` and it seems to work for me, it's not as nice as the default pager as you don't have `less` like navigation but at least it's something to avoid very long outputs
