### ISSUE TITLE
After running tests or any zeus command terminal text disappears 

### ISSUE THREAD

**Issue by jeremiahlukus** [burke/zeus#636]
After running tests or any zeus commands terminal text disappears. 

![screen shot 2017-05-11 at 15 51 37](https://cloud.githubusercontent.com/assets/17206638/25969127/cd33d30a-3661-11e7-8977-b92acb284210.png)

You can see I typed `zspec` to run my tests. After the test finished I ran the same command but now no text is shown. I have to close out the terminal to be able to see what I type again.

**Comment by sideshowcoder** [comment]
This is related to #624 a fix is in the PR #633 which is not merged yet.

**Comment by sideshowcoder** [comment]
Please check `0.15.14.pre` released, please check if it improves things.
