### ISSUE TITLE
omg if this doesnt get fixed im going to explode... this is a mission critical bug...! 

### ISSUE THREAD

**Issue by staycreativedesign** [burke/zeus#643]
`zeus rake routes | lolcat` 

gives me that... 

![2017-08-31_17-16-50](https://user-images.githubusercontent.com/1952722/29947673-86b3d26a-8e70-11e7-9f8e-9bdf454d2217.png)

**Comment by sideshowcoder** [comment]
Indention is hard, any ideas welcome.

**Comment by Soloxwd** [comment]
cool
