### ISSUE TITLE
slavenode.go:226: [test_environment] read unix @->@: EOF

### ISSUE THREAD

**Issue by xero88** [burke/zeus#652]
slavenode.go:226: [test_environment] read unix @->@: EOF

**Comment by nickiesiva** [comment]
I have the same issue. 

I got `slavenode.go:226: [cucumber_environment] read unix ->: EOF` when start zeus on my machine. All commands is available, except _cucumber_ command (crashed).

When I ran `zeus parallel_rspec ./spec/controllers/api/ -n 2 -o '-t smoke'`,
 I got `fish: 'zeus parallel_rspec ./spec/cont…' terminated by signal SIGTERM (Polite quit request)`

Why _rspec_ command got that error ?

**Comment by xero88** [comment]
I resolved with by relaunching the server `bin/rails s` and then the errors are displayed

**Comment by lacostenycoder** [comment]
I'm having this issue now... can this be reopened? I have no solution.
