### ISSUE TITLE
Pry not used in place of IRB with zeus console

### ISSUE THREAD

**Issue by aiwilliams** [burke/zeus#66]
I am using Pry and a gem (https://github.com/rweng/pry-rails) to make it my REPL when I run `rails console`. I have verified the latter to function properly, though when I run `zeus console`, I only get IRB (sad pandas, really, I think). Of course, I can simply type `Pry.start`, so this is likely low priority, but I thought you should know. Let me know if I can help somehow more.

**Comment by davidcpell** [comment]
Just ran into this issue. I'm using a later version of `pry-rails` (0.3.4) and getting the original problem described.
